server:
  port: 8088
spring:
  application:
    name: blog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mybatis-plus:
#    global-config:
#      db-config:
#        logic-delete-field: isDelete
#        logic-delete-value: 1
#        logic-not-delete-value: 0
#        id-type: auto
  global-config:
    db-config:
      id-type: auto



